"""created and added a restaurants_pizza table

Revision ID: 72ad28787b3f
Revises: 96d8a33924fd
Create Date: 2023-09-27 14:54:53.455611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72ad28787b3f'
down_revision = '96d8a33924fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
